# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d5cbe27a3a8408e7b46b60fb1c187d9e2380941b9e65d76d6230eb1bd0e5b7bbe4d25d5fe33474b2cb0b85a999638a936b73e34f802ae6f7dd030576efa4f31

test:
  secret_key_base: 934cfad858c7124b76841210ef31bf3ee0d7303be5482d8ab9e34eb4901b2988bb2c9f420e9d9435fbf46f9831dd25a6c8bc980d3f3800a2274c75a3da79f8c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
